### PR TITLE
use ph_with instead of ph_with_* functions

### PR DESCRIPTION
**Pull request by davidgohel**
Dear Tom,

This PR should help in adjusting your code to the usage of `officer::ph_with` and
`rvg::dml` instead of functions `officer::ph_with_*` that should be deprecated soon.

Let me know if you have questions about ph_with.

KR,
David

### CODE REVIEW

**Comment by davidgohel** [comment]
Dear Tom, just to let you know I am about to submit rvg to CRAN and package {export} is still failling on revdeps check because of deprecation of `ph_with_` in rvg (also in officer after). 

KR
David

**Comment by davidgohel** [comment]
Dear Tom, in the next release of `flextable`, `ph_with_flextable` will also be deprecated, `ph_with_flextable_at` has just been deprecated. 

Let me know if you have a question

KR

**Comment by cvanderaa** [comment]
Dear @davidgohel,

Thank you very much for your contribution and sorry for our lack of reactivity.

**Comment by davidgohel** [comment]
@cvanderaa no problem :) thanks for merging

**Pull request merged**
